spring:
  application:
    name: remote-falcon-external-api
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  servlet:
    contextPath: /remote-falcon-external-api
  port: 8080

info:
  build:
    artifact: remote-falcon-external-api

management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: "OPTIONS, GET, POST, PUT, DELETE"
        allowed-headers: "*"